# Generated by Django 4.1 on 2022-09-25 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task", old_name="datacompleted", new_name="datecompleted",
        ),
    ]
